version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  moodle:
    image: bitnami/moodle:4.1.2
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - moodle:/bitnami
    environment:
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: localhost
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: root
      MOODLE_DATABASE_PASSWORD: 12345
      MOODLE_USERNAME: user
      MOODLE_PASSWORD: root
      MOODLE_SKIP_BOOTSTRAP: "yes"
    depends_on:
        - db
volumes:
  db:
  moodle:
